In [1]:
import pandas as pd

df = pd.read_csv('../data/nbadata.csv')

In [2]:

print(df.info())
print(df.columns.tolist())

<class 'pandas.DataFrame'>
RangeIndex: 28716 entries, 0 to 28715
Data columns (total 29 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      28716 non-null  str
 1   Tm          28716 non-null  str
 2   Opp         28716 non-null  str
 3   Result      28716 non-null  str
 4   MP          28716 non-null  str
 5   FG          28716 non-null  float64
 6   FGA         28716 non-null  float64
 7   FG%         27206 non-null  float64
 8   3P          28716 non-null  float64
 9   3PA         28716 non-null  float64
 10  3P%         22941 non-null  float64
 11  FT          28716 non-null  float64
 12  FTA         28716 non-null  float64
 13  FT%         16030 non-null  float64
 14  ORB         28716 non-null  float64
 15  DRB         28716 non-null  float64
 16  TRB         28716 non-null  float64
 17  AST         28716 non-null  float64
 18  STL         28716 non-null  float64
 19  BLK         28716 non-null  float64
 20  TOV         28716 non-null  float64
 21  PF          28716 non-null  float64
 22  PTS         28716 non-null  float64
 23  +/-         28686 non-null  float64
 24  GmSc        28716 non-null  float64
 25  Date        28716 non-null  str
 26  Unnamed: 0  0 non-null      float64
 27  Unnamed: 1  0 non-null      float64
 28  Unnamed: 2  0 non-null      float64
dtypes: float64(23), str(6)
memory usage: 7.3 MB
None
['Player', 'Tm', 'Opp', 'Result', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+/-', 'GmSc', 'Date', 'Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2']

In [3]:
print('FG% Null:')
print(df.loc[:, 'FG%'].isna().sum())
print('3P% Null: ')
print(df.loc[:, '3P%'].isna().sum())
print('FT Null:')
print(df.loc[:, 'FT%'].isna().sum())
print('+/-% Null:')
print(df.loc[:, '+/-'].isna().sum())

FG% Null:
1510
3P% Null:
5775
FT Null:
12686
+/-% Null:
30

In [4]:
same_size_FG = (len(df.loc[(df['FG%'].isna()) & (df['FGA'] == 0)]) == len(df.loc[(df['FG%'].isna())]))
print(same_size_FG)

same_size_FT = (len(df.loc[(df['FT%'].isna()) & (df['FTA'] == 0)]) == len(df.loc[(df['FT%'].isna())]))
print(same_size_FT)

same_size_3P = (len(df.loc[(df['3P%'].isna()) & (df['3PA'] == 0)]) == len(df.loc[(df['3P%'].isna())]))
print(same_size_3P)

True
True
True

In [5]:
pd.set_option('display.max_columns', None)
df.loc[df['+/-'].isna()]

,Player,Tm,Opp,Result,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+/-,GmSc,Date,Unnamed: 0,Unnamed: 1,Unnamed: 2
593,Moussa Cisse,DAL,WAS,L,0:17,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2025-10-24,NaN,NaN,NaN
596,Dwight Powell,DAL,WAS,L,0:17,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2025-10-24,NaN,NaN,NaN
8465,OG Anunoby,NYK,SAS,W,40:01,10.0,17.0,0.588,5.0,10.0,0.500,3.0,5.0,0.600,4.0,5.0,9.0,3.0,0.0,1.0,0.0,4.0,28.0,NaN,24.8,2025-12-16,NaN,NaN,NaN
8466,Dylan Harper,SAS,NYK,L,28:23,7.0,14.0,0.500,5.0,7.0,0.714,2.0,2.0,1.000,3.0,4.0,7.0,0.0,0.0,0.0,0.0,3.0,21.0,NaN,16.1,2025-12-16,NaN,NaN,NaN
8467,Stephon Castle,SAS,NYK,L,34:54,5.0,15.0,0.333,1.0,3.0,0.333,4.0,5.0,0.800,4.0,3.0,7.0,12.0,0.0,1.0,2.0,4.0,15.0,NaN,15.3,2025-12-16,NaN,NaN,NaN
8468,Luke Kornet,SAS,NYK,L,22:45,7.0,9.0,0.778,0.0,0.0,NaN,0.0,0.0,NaN,5.0,1.0,6.0,1.0,0.0,0.0,0.0,0.0,14.0,NaN,15.0,2025-12-16,NaN,NaN,NaN
8469,Karl-Anthony Towns,NYK,SAS,W,29:40,6.0,12.0,0.500,2.0,5.0,0.400,2.0,2.0,1.000,4.0,7.0,11.0,1.0,2.0,0.0,2.0,3.0,16.0,NaN,14.4,2025-12-16,NaN,NaN,NaN
8470,Josh Hart,NYK,SAS,W,29:16,5.0,7.0,0.714,1.0,3.0,0.333,0.0,0.0,NaN,1.0,7.0,8.0,3.0,2.0,1.0,1.0,4.0,11.0,NaN,13.1,2025-12-16,NaN,NaN,NaN
8471,Tyler Kolek,NYK,SAS,W,20:27,5.0,9.0,0.556,2.0,5.0,0.400,2.0,2.0,1.000,0.0,5.0,5.0,5.0,0.0,0.0,1.0,2.0,14.0,NaN,12.9,2025-12-16,NaN,NaN,NaN
8472,Jalen Brunson,NYK,SAS,W,41:03,11.0,27.0,0.407,1.0,5.0,0.200,2.0,4.0,0.500,1.0,3.0,4.0,8.0,0.0,1.0,4.0,3.0,25.0,NaN,12.4,2025-12-16,NaN,NaN,NaN
8473,Victor Wembanyama,SAS,NYK,L,24:54,7.0,17.0,0.412,2.0,6.0,0.333,2.0,4.0,0.500,0.0,6.0,6.0,1.0,1.0,2.0,1.0,0.0,18.0,NaN,12.0,2025-12-16,NaN,NaN,NaN
8474,Harrison Barnes,SAS,NYK,L,23:28,4.0,9.0,0.444,0.0,4.0,0.000,3.0,3.0,1.000,2.0,1.0,3.0,2.0,1.0,1.0,0.0,0.0,11.0,NaN,11.1,2025-12-16,NaN,NaN,NaN
8475,Mitchell Robinson,NYK,SAS,W,18:22,2.0,6.0,0.333,0.0,0.0,NaN,0.0,0.0,NaN,10.0,5.0,15.0,2.0,1.0,2.0,1.0,3.0,4.0,NaN,10.7,2025-12-16,NaN,NaN,NaN
8476,De'Aaron Fox,SAS,NYK,L,31:40,5.0,13.0,0.385,2.0,6.0,0.333,4.0,6.0,0.667,0.0,2.0,2.0,9.0,1.0,0.0,5.0,3.0,16.0,NaN,9.8,2025-12-16,NaN,NaN,NaN
8477,Jordan Clarkson,NYK,SAS,W,26:40,6.0,15.0,0.400,3.0,7.0,0.429,0.0,0.0,NaN,2.0,0.0,2.0,0.0,1.0,1.0,0.0,1.0,15.0,NaN,9.6,2025-12-16,NaN,NaN,NaN
8478,Mikal Bridges,NYK,SAS,W,32:38,4.0,12.0,0.333,1.0,5.0,0.200,2.0,2.0,1.000,1.0,4.0,5.0,5.0,0.0,0.0,1.0,0.0,11.0,NaN,8.6,2025-12-16,NaN,NaN,NaN
8479,Devin Vassell,SAS,NYK,L,33:17,4.0,14.0,0.286,2.0,7.0,0.286,2.0,2.0,1.000,0.0,5.0,5.0,3.0,0.0,0.0,0.0,2.0,12.0,NaN,6.6,2025-12-16,NaN,NaN,NaN
8480,Keldon Johnson,SAS,NYK,L,15:37,1.0,3.0,0.333,1.0,2.0,0.500,0.0,0.0,NaN,3.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,3.0,NaN,3.7,2025-12-16,NaN,NaN,NaN
8481,Julian Champagnie,SAS,NYK,L,25:02,1.0,5.0,0.200,1.0,4.0,0.250,0.0,0.0,NaN,1.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,3.0,NaN,2.9,2025-12-16,NaN,NaN,NaN
8482,Ariel Hukporti,NYK,SAS,W,1:52,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,NaN,1.0,2025-12-16,NaN,NaN,NaN
12949,Kelly Olynyk,SAS,OKC,L,0:00,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-01-13,NaN,NaN,NaN
12950,Nick Richards,PHO,MIA,L,0:00,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-01-13,NaN,NaN,NaN
14578,Tony Bradley,IND,OKC,W,0:00,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-01-23,NaN,NaN,NaN
18988,Trayce Jackson-Davis,TOR,SAS,L,0:01,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.3,2026-02-25,NaN,NaN,NaN
19192,Maxi Kleber,LAL,PHO,L,0:00,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-02-26,NaN,NaN,NaN
24429,Max Shulga,BOS,ATL,L,0:17,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-03-30,NaN,NaN,NaN
24430,John Tonje,BOS,ATL,L,0:17,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-03-30,NaN,NaN,NaN
24784,Hugo González,BOS,MIA,W,0:08,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-04-01,NaN,NaN,NaN
24787,Max Shulga,BOS,MIA,W,0:08,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-04-01,NaN,NaN,NaN
28415,Aaron Wiggins,OKC,SAS,W,0:10,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,2026-05-20,NaN,NaN,NaN

In [6]:
null_plus_minus = df.loc[df['+/-'].isna()]
result = null_plus_minus.groupby(['Date', 'Tm', 'Opp']).size()
print(result)

Date        Tm   Opp
2025-10-24  DAL  WAS    2
2025-12-16  NYK  SAS    9
            SAS  NYK    9
2026-01-13  PHO  MIA    1
            SAS  OKC    1
2026-01-23  IND  OKC    1
2026-02-25  TOR  SAS    1
2026-02-26  LAL  PHO    1
2026-03-30  BOS  ATL    2
2026-04-01  BOS  MIA    2
2026-05-20  OKC  SAS    1
dtype: int64

In [7]:
df.loc[df['MP'] == '0:00']

df_raw = df.copy()
df = (df.loc[~(df['MP'] == '0:00')]).copy()

In [8]:
print(df_raw.shape)
print(df.shape)

(28716, 29)
(28712, 29)

In [9]:
df.columns.tolist()

['Player',
 'Tm',
 'Opp',
 'Result',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 '+/-',
 'GmSc',
 'Date',
 'Unnamed: 0',
 'Unnamed: 1',
 'Unnamed: 2']

In [10]:
notnull = df.loc[(~(df['Unnamed: 0'].isna())) & (~(df['Unnamed: 1'].isna())) & (~(df['Unnamed: 2'].isna()))]

if notnull.empty:
    df = df.drop(columns=['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2'])

In [11]:
print(df.shape)
print(df.columns)

(28712, 26)
Index(['Player', 'Tm', 'Opp', 'Result', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
       '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
       'TOV', 'PF', 'PTS', '+/-', 'GmSc', 'Date'],
      dtype='str')

In [12]:
keldon_games = df.loc[((df['Player'] == 'Keldon Johnson'))]
keldon_games['Date'].nunique()

106

In [13]:
df_by_player = df.groupby('Player')[['PTS','AST','TRB']].mean().round(2)
df_by_player.head()

                 PTS   AST   TRB
Player
A.J. Green     10.37  1.95  2.73
A.J. Lawson     3.65  0.35  1.48
AJ Johnson      3.33  0.98  1.15
Aaron Gordon   15.79  2.64  5.77
Aaron Holiday   5.21  1.00  0.95

In [14]:
games = df.groupby('Player').size()
print(type(games))
df_by_player['Games'] = games
df_by_player.head()

<class 'pandas.Series'>

                 PTS   AST   TRB  Games
Player
A.J. Green     10.37  1.95  2.73     78
A.J. Lawson     3.65  0.35  1.48     31
AJ Johnson      3.33  0.98  1.15     48
Aaron Gordon   15.79  2.64  5.77     39
Aaron Holiday   5.21  1.00  0.95     63

In [15]:
fg_sum = df.groupby('Player')['FG'].sum()
fga_sum = df.groupby('Player')['FGA'].sum()
fg_pct = (fg_sum/fga_sum *100).round(2)
df_by_player['FG%'] = fg_pct
df_by_player.head()


print(df_by_player['FG%'].isna().sum())

0

In [16]:
sum_3pa = df.groupby('Player')['3PA'].sum()
sum_3p = df.groupby('Player')['3P'].sum()
pct_3p = (sum_3p/sum_3pa *100).round(2)
df_by_player['3P%'] = pct_3p
df_by_player.head()

print(df_by_player['3P%'].isna().sum())

34

In [17]:
sum_FTA = df.groupby('Player')['FTA'].sum()
sum_FT = df.groupby('Player')['FT'].sum()
pct_FT = (sum_FT/sum_FTA *100).round(2)
df_by_player['FT%'] = pct_FT
df_by_player.head()

print(df_by_player['FT%'].isna().sum())

19

In [18]:
def minutes_to_decimal(tempo: str) -> float:
    partes = tempo.split(':')
    minutos = int(partes[0])
    segundos = int(partes[1]) / 60
    partes = round(minutos+segundos,2)
    return partes

df_minutes_to_decimal = df['MP'].apply(minutes_to_decimal)
df_minutes_to_decimal.head()

0    40.98
1    48.88
2    34.73
3    47.22
4    36.33
Name: MP, dtype: float64

In [19]:
df['MPG'] = df_minutes_to_decimal
df[['MP', 'MPG']].head()

df_by_player['MPG'] = df.groupby('Player')['MPG'].mean().round(2)
df_by_player.head()

                 PTS   AST   TRB  Games    FG%    3P%    FT%    MPG
Player
A.J. Green     10.37  1.95  2.73     78  42.39  41.88  85.48  29.10
A.J. Lawson     3.65  0.35  1.48     31  40.43  39.62  80.00   8.93
AJ Johnson      3.33  0.98  1.15     48  32.39  21.05  85.00   9.45
Aaron Gordon   15.79  2.64  5.77     39  49.07  37.43  76.30  28.06
Aaron Holiday   5.21  1.00  0.95     63  40.51  38.38  85.37  13.45

In [20]:
df_by_player.reset_index()

              Player    PTS   AST   TRB  Games    FG%    3P%     FT%    MPG
0         A.J. Green  10.37  1.95  2.73     78  42.39  41.88   85.48  29.10
1        A.J. Lawson   3.65  0.35  1.48     31  40.43  39.62   80.00   8.93
2         AJ Johnson   3.33  0.98  1.15     48  32.39  21.05   85.00   9.45
3       Aaron Gordon  15.79  2.64  5.77     39  49.07  37.43   76.30  28.06
4      Aaron Holiday   5.21  1.00  0.95     63  40.51  38.38   85.37  13.45
..               ...    ...   ...   ...    ...    ...    ...     ...    ...
577      Zach LaVine  19.18  2.28  2.77     39  47.90  38.98   88.03  31.39
578       Zeke Nnaji   3.70  0.56  2.57     54  47.71  27.27   78.00  11.95
579  Ziaire Williams  10.23  1.07  2.39     56  42.49  34.26   85.00  22.88
580  Zion Williamson  21.00  3.21  5.69     62  59.98  25.00   71.61  29.69
581      Zyon Pullin   4.60  1.80  0.60      5  69.23  33.33  100.00   8.52

[582 rows x 9 columns]

In [30]:
#exploring to create player table with game date vs points.
selected = 'A.J. Lawson'
player_games_by_date = df.loc[df['Player'] == selected, ['Date', 'PTS']].sort_values(by='Date')
player_games_by_date['Date'] = pd.to_datetime(player_games_by_date['Date'])
player_games_by_date.head()

            Date   PTS
7704  2025-12-07  10.0
7869  2025-12-09   2.0
9946  2025-12-26   2.0
12298 2026-01-09   3.0
12639 2026-01-11   2.0